# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JitsiMeet' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JitsiMeet

end

target 'JitsiMeetBroadcastExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JitsiMeetBroadcastExtension

end

target 'JitsiMeetCompanion' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JitsiMeetCompanion

end

target 'JitsiMeetCompanion Extension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JitsiMeetCompanion Extension

end
